### ISSUE TITLE
建议yaml 文件请标注下训练的设备信息

### ISSUE THREAD

**Issue by vigo999** [mindspore-lab/mindyolo#105]
modelname_scale_device.
yolov8_s_ascend_910.yaml
yolov8_s_gpu_3090.yaml

**Comment by zhanghuiyao** [comment]
这是个好主意，不过这样可能还是不够清晰，如果把bs、epoch、dataset的信息都加上是不是会更清晰
modelname_scale_[option]feature_bs_epochs_dataset_device.
yolov8_l_syncbn_8xb16_500e_coco_ascend910.py
