### ISSUE TITLE
在openi上运行test.py报错

### ISSUE THREAD

**Issue by Ash-Lee233** [mindspore-lab/mindyolo#106]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
> Uncomment only one ` /device <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> `/device ascend`</br>

### Software Environment:
- **MindSpore version (source or binary)**:
- **Python version (e.g., Python 3.7.5)**:
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**:
- **GCC/Compiler version (if compiled from source)**: 

## Describe the current behavior
在启智运行yolox-nano的test.py时报错
![d6f90bcba7877f9b3920882e7966bfd](https://github.com/mindspore-lab/mindyolo/assets/49091981/f1ad16b9-883f-44b1-8ddd-d41a797b3395)

## Describe the expected behavior
运行并得到推理结果

## Steps to reproduce the issue
1. python test.py --config ./configs/yolox/yolox-nano.yaml --weight yolox-nano.ckpt
2. 
3.

**Comment by yuedongli1** [comment]
Openi的调试环境中pycocotools的默认版本为2.0.0，需卸载更新至2.0.2版本。
