### ISSUE TITLE
MindYOLO代码易用性问题记录

### ISSUE THREAD

**Issue by CaitinZhao** [mindspore-lab/mindyolo#120]
**If this is your first time, please read our contributor guidelines:** https://gitee.com/mindspore/mindspore/blob/master/CONTRIBUTING.md

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

MindYOLO目前的版本存在一些语法的规避，和框架的易用性问题，在这个issue记录一下

**Describe alternatives you've considered**

**Additional context**

**Comment by CaitinZhao** [comment]
1. loss部分冗余代码太多，比如 xywh2xyxy， to_tensor，在多个模型的loss中重复定义，需要提取公共函数

**Comment by CaitinZhao** [comment]
loss中使用stop_gradient太多，很难找到截断梯度的作用范围，后面2.0会提供类似torch的with torch.no_grad()方式

**Comment by CaitinZhao** [comment]
代码中使用了大量的tuple操作，后续改成python常用的list操作

**Comment by CaitinZhao** [comment]
现有的架构对loss的个数，输入的个数限制比较大，后续版本升级后改成dict的方式

**Comment by xunfeng2zkj** [comment]
不兼容mindspore-1.8.0

**Comment by zhiqwang** [comment]
有计划支持 ONNX 导出吗？
