### ISSUE TITLE
        topk_metrics, topk_idxs = ops.top_k(metrics, self.topk)  # (b, n_gt, topk)

### ISSUE THREAD

**Issue by xunfeng2zkj** [mindspore-lab/mindyolo#169]
2.0上应该是这样？        
topk_metrics, topk_idxs = ops.topk(metrics, self.topk)  # (b, n_gt, topk)

**Comment by zhanghuiyao** [comment]
看起来没什么问题，接口用法可以参考文档[topk](https://www.mindspore.cn/docs/zh-CN/r2.0/api_python/ops/mindspore.ops.topk.html?highlight=topk#mindspore.ops.topk)

**Comment by xunfeng2zkj** [comment]
> 2.0上应该是这样？ topk_metrics, topk_idxs = ops.topk(metrics, self.topk) # (b, n_gt, topk)

脑壳疼，一个都跑步起来

**Comment by zhanghuiyao** [comment]
建议使用指定的mindspore版本，其他版本可能会存在版本适配问题，mindspore安装可以[参考](https://www.mindspore.cn/install/en)
mindyolo-r0.1分支对应mindspore 1.8.1(以及对应的cann版本)
mindyolo-master分支对应mindspore 2.0(以及对应的cann版本)
