### ISSUE TITLE
基于自定义数据集进行训练，会卡住Warning

### ISSUE THREAD

**Issue by RitzLu** [mindspore-lab/mindyolo#174]
我在用MindYOLO（YOLOv7）训练一个我自己的数据集，它一直卡在这个wanring，一直重复输出这个日志几个小时还没停。
![image](https://github.com/mindspore-lab/mindyolo/assets/22465325/812b5fcd-d5bc-4bb9-9033-fe868db5c6d0)
用的是r0.1分支，mindspore版本号是1.9

**Comment by kv1830** [comment]
可以看看前面的日志，是不是抛异常了

**Comment by zhanghuiyao** [comment]
看起来有可能是别的地方报错了 导致这里数据在等待 最后超时
