### ISSUE TITLE
CPU环境下mindir的推理不正确(运行报错,Segmentation fault,结果不准确)

### ISSUE THREAD

**Issue by longvoyage** [mindspore-lab/mindyolo#175]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
 `/device cpu`</br>

### Software Environment:
- **MindSpore version (source or binary)**:2.0
- **Python version (e.g., Python 3.7.5)**:3.7.5
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 
- **GCC/Compiler version (if compiled from source)**: 

## Describe the current behavior
CPU环境下mindir的推理不正确(运行报错,Segmentation fault,结果不准确)
以下mindspore全部在CPU上运行
mindspore 2.0
master分支

1.文档有问题,代码有问题

deploy/README.md
Lite Predict
python deploy/predict.py --model_type Lite --model_path ./yolov5n.mindir --conifg ./configs/yolov5/yolov5n.yaml --image_path ./coco/image/val2017/image.jpg

里面有个单词拼写错误, --conifg, 应该是 --config

deploy/infer_engine/lite.py
lite 固定设置为ascend, 需要根据配置动态修改
context.target = ["ascend"]

2.Yolov5s
ckpt直接推理 OK
mindir lite推理报错

`[ERROR] LITE(57734,7fe3b06fb740,python):2023-07-27-09:27:21.431.266 [mindspore/lite/tools/converter/legacy_optimizer/graph/dropout_node_remove_pass.cc:35] IsolateDropoutNode] Only support node who has no more than one input and two output
[ERROR] LITE(57734,7fe3b06fb740,python):2023-07-27-09:27:21.431.286 [mindspore/lite/tools/converter/legacy_optimizer/graph/dropout_node_remove_pass.cc:106] Run] IsolateDropoutNode failed, subGraph: , node: Default/model-Model/model-CellList/24-YOLOv5Head/TensorScatterUpdate-op914, error: -1
[ERROR] LITE(57734,7fe3b06fb740,python):2023-07-27-09:27:21.431.299 [mindspore/lite/tools/converter/optimizer.cc:78] Run] Run GraphPass failed
[ERROR] LITE(57734,7fe3b06fb740,python):2023-07-27-09:27:21.431.310 [mindspore/lite/tools/converter/graphdef_transform.cc:92] Transform] Run unused_op_remove_optimizer graphPasses Failed
[ERROR] LITE(57734,7fe3b06fb740,python):2023-07-27-09:27:21.431.322 [mindspore/lite/tools/converter/converter_metagraph.cc:102] Build] Transform meta graph failed -1
[ERROR] ME(57734,7fe3b06fb740,python):2023-07-27-09:27:21.432.768 [mindspore/lite/src/extendrt/delegate/graph_executor/litert/graph_executor.cc:131] CompileGraph] func graph convert to meta graph failed.
[ERROR] ME(57734,7fe3b06fb740,python):2023-07-27-09:27:21.432.791 [mindspore/lite/src/extendrt/session/delegate_session.cc:167] CompileGraph] GraphSinkSession::CompileGraph compile graph failed
[ERROR] ME(57734,7fe3b06fb740,python):2023-07-27-09:27:21.432.808 [mindspore/lite/src/extendrt/cxx_api/model/model_impl.cc:190] BuildByBufferImpl] compile graph failed.
Traceback (most recent call last):
  File "deploy_predict.py", line 207, in <module>
    infer(args)
  File "deploy_predict.py", line 173, in infer
    network = LiteModel(args.model_path)
  File "/home/xxx/mindyolo-master/infer_engine/lite.py", line 12, in __init__
    self._init_model()
  File "/home/xxx/mindyolo-master/infer_engine/lite.py", line 22, in _init_model
    self.model.build_from_file(self.model_path, mslite.ModelType.MINDIR, context)
  File "/root/miniconda3/envs/xxx/lib/python3.7/site-packages/mindspore_lite/model.py", line 178, in build_from_file
    raise RuntimeError(f"build_from_file failed! Error is {ret.ToString()}")
RuntimeError: build_from_file failed! Error is Common error code.
`

3.yolov7-tiny
ckpt直接推理 OK
mindir lite推理 Segmentation fault

4.yolov8n
lite推理 NG
置信度都是1.0

![image](https://github.com/mindspore-lab/mindyolo/assets/6425773/ca1c2e42-9745-4c19-b3be-ed7d8b63968b)

Ckpt直接推理 OK
![image](https://github.com/mindspore-lab/mindyolo/assets/6425773/a4b202e1-45d4-4025-899b-1c06af4b8fd1)

5.Yolox-n

Mindir 转ms报错

`[ERROR] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.907.053 [mindspore/lite/tools/optimizer/common/gllo_utils.cc:1143] FetchShapeFromAbstract] abstract of cnode is invalid.
[ERROR] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.907.074 [mindspore/lite/tools/optimizer/format/delete_redundant_transpose.cc:77] DeleteNot4DTranspose] fetch shape failed.
[ERROR] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.907.107 [mindspore/lite/tools/optimizer/format/delete_redundant_transpose.cc:261] Run] delete not 4D transpose failed.
[ERROR] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.907.118 [mindspore/lite/tools/optimizer/graph/decrease_transpose_algo.cc:880] Run] Run delete-redundant-transpose pass failed.
[WARNING] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.907.129 [mindspore/lite/tools/converter/optimizer_manager.cc:65] RunOptimizerPass] run pass failed, pass name is DecreaseTransposeAlgo
[ERROR] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.907.139 [mindspore/lite/tools/converter/anf_transform.cc:587] DoFormatForMindIR] Run ToNCHWFormat pass failed
[ERROR] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.907.162 [mindspore/lite/tools/converter/anf_transform.cc:852] Transform] optimizer failed.
[ERROR] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.907.174 [mindspore/lite/tools/converter/converter_funcgraph.cc:448] Optimize] Transform anf graph failed.
[ERROR] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.908.812 [mindspore/lite/tools/converter/converter.cc:1031] HandleGraphCommon] Optimize func graph failed: -2 NULL pointer returned.
[ERROR] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.912.239 [mindspore/lite/tools/converter/converter.cc:981] Convert] Handle graph failed: -2 NULL pointer returned.
[ERROR] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.912.257 [mindspore/lite/tools/converter/converter.cc:1168] RunConverter] Convert model failed
[ERROR] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.912.268 [mindspore/lite/tools/converter/converter_context.h:60] PrintOps] ===========================================
[ERROR] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.912.277 [mindspore/lite/tools/converter/converter_context.h:61] PrintOps] UNSUPPORTED OP LIST:
[ERROR] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.912.287 [mindspore/lite/tools/converter/converter_context.h:63] PrintOps] FMKTYPE: , OP TYPE: SiLU
[ERROR] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.912.296 [mindspore/lite/tools/converter/converter_context.h:63] PrintOps] FMKTYPE: , OP TYPE: make_list
[ERROR] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.912.305 [mindspore/lite/tools/converter/converter_context.h:65] PrintOps] ===========================================
[ERROR] LITE(57727,7f78fced0f40,converter_lite):2023-07-27-09:25:42.912.317 [mindspore/lite/tools/converter/cxx_api/converter.cc:334] Convert] Convert model failed, ret=NULL pointer returned.
ERROR [mindspore/lite/tools/converter/converter_lite/main.cc:102] main] Convert failed. Ret: NULL pointer returned.
Convert failed. Ret: NULL pointer returned.
`

**Comment by zhanghuiyao** [comment]
当前仅在ascend310设备上进行mindir推理，cpu设备上请使用ckpt推理。
