### ISSUE TITLE
执行yolov8在train.py下调整训练次数epoch出错

### ISSUE THREAD

**Issue by southofwall** [mindspore-lab/mindyolo#176]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
> mindspore1.8.0-cann5.1.2-py3.7-euler2.8.3
### Software Environment:
- **MindSpore version (source or binary)**:
- **Python version (e.g., Python 3.7.5)**:
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**:
- **GCC/Compiler version (if compiled from source)**: 

## Describe the current behavior
执行yolov8在train.py下调整训练次数epoch出错

## Describe the expected behavior
5 ->100

## Steps to reproduce the issue
1. 在终端命令中添加 --epoch 100
2. 加载参数成功
3.运行报错

## Related log / screenshot
Traceback (most recent call last):
  File "train.py", line 301, in <module>
    train(args)
  File "train.py", line 150, in train
    assert sum(stage_epochs) == args.epochs, f"Stage epochs [{sum(stage_epochs)}] not equal args.epochs [{args.epochs}]"
AssertionError: Stage epochs [5] not equal args.epochs [100]

## code
    transforms = args.data.train_transforms
    stage_dataloaders = []
    print(transforms)
    stage_epochs = [args.epochs,]   if not isinstance(transforms, dict) else transforms['stage_epochs']
    stage_transforms = [transforms,] if not isinstance(transforms, dict) else transforms['trans_list']
    assert len(stage_epochs) == len(stage_transforms), "The length of transforms and stage_epochs is not equal."
    assert sum(stage_epochs) == args.epochs, f"Stage epochs [{sum(stage_epochs)}] not equal args.epochs [{args.epochs}]"

**Comment by zhanghuiyao** [comment]
yolov8 的数据增强是两段式的 修改epochs的同时还要修改 'data.train_transforms.stage_epochs'
https://github.com/mindspore-lab/mindyolo/blob/master/configs/yolov8/hyp.scratch.high.yaml#L28
<img width="473" alt="image" src="https://github.com/mindspore-lab/mindyolo/assets/20476835/602fa9b1-1d5e-4936-b7ff-98aa049b0647">
