### ISSUE TITLE
执行yolov8执行test.py下报错结果与coco set不匹配

### ISSUE THREAD

**Issue by southofwall** [mindspore-lab/mindyolo#177]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
mindspore1.8.0-cann5.1.2-py3.7-euler2.8.3

## Describe the current behavior
执行test

## Describe the expected behavior
yolov8下test.py下报错结果与coco set不匹配

## Steps to reproduce the issue
1. 按照官方.md执行测试
2. python test.py --config ./configs/yolov8/yolov8n.yaml --weight=./weights/yolo8-n_500e_mAP372-cc07f5bd.ckpt
3.

## Related log / screenshot
index created!
Loading and preparing results...
2023-07-28 10:47:13,404 [ERROR]pycocotools unable to run:Results do not correspond to current coco set
Traceback (most recent call last):
File "test.py",line 275,in <module>
main(args）
File "test.py",line 266,in main
per_batch_size=args.per_batch_size,
File "test.py",line 200,in test
raise e
File "test.py",line 189,in test
pred anno.loadRes(result dicts)
File "/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/pycocotools/coco.py",line 328,in loadRes
'Results do not correspond to current coco set'
AssertionError:Results do not correspond to current coco set

**Comment by zhanghuiyao** [comment]
看起来是pycocotools接口的问题，可以尝试检查下coco val set的annotations文件和val文件夹下图片是否正确

**Comment by southofwall** [comment]
> 看起来是pycocotools接口的问题，可以尝试检查下coco val set的annotations文件和val文件夹下图片是否正确

老师您好，检测过程中发现在yolov8中我训练的类别有89种，而annotations中instances_val2017.json的categories只有80items，不知道是不是这个原因。如果是，是否应该在instances_val2017.json文件中补上我添加的标签即可。val文件夹下图片路径正确。

**Comment by zhanghuiyao** [comment]
> > 看起来是pycocotools接口的问题，可以尝试检查下coco val set的annotations文件和val文件夹下图片是否正确
> 
> 老师您好，检测过程中发现在yolov8中我训练的类别有89种，而annotations中instances_val2017.json的categories只有80items，不知道是不是这个原因。如果是，是否应该在instances_val2017.json文件中补上我添加的标签即可。val文件夹下图片路径正确。

您用的是自定义数据集吗 是的话可以参考以下example，https://github.com/mindspore-lab/mindyolo/tree/master/examples/finetune_SHWD

**Comment by southofwall** [comment]
> > > 看起来是pycocotools接口的问题，可以尝试检查下coco val set的annotations文件和val文件夹下图片是否正确
> > 
> > 
> > 老师您好，检测过程中发现在yolov8中我训练的类别有89种，而annotations中instances_val2017.json的categories只有80items，不知道是不是这个原因。如果是，是否应该在instances_val2017.json文件中补上我添加的标签即可。val文件夹下图片路径正确。
> 
> 您用的是自定义数据集吗 是的话可以参考以下example，https://github.com/mindspore-lab/mindyolo/tree/master/examples/finetune_SHWD

谢谢老师，上面的问题已经解决，训练和预测的比较成功，但是在对模型进行指标评估时，我调好了test.py内的json文件的coco.yaml对应的val_set，可是运行后的结果时这样的。
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
2023-08-01 16:50:43,651 [INFO] Speed: 6.9/53.0/59.8 ms inference/NMS/total per 640x640 image at batch-size 16;
2023-08-01 16:50:49,880 [INFO] Testing completed.

**Comment by zhanghuiyao** [comment]
这个看起来是没有精度 可以尝试infer单张图片可视化一下结果

**Comment by Versua0** [comment]
> 这个看起来是没有精度 可以尝试infer单张图片可视化一下结果

你好，我将推理结果的result_dict保存了下来，发现其中的image_id不是从0/1开始的，初始值刚好为train数据集的数量，而当我将image_id减去这个数值后【Results do not correspond to current coco set】的问题能够解决，但是结果却是
![image](https://github.com/mindspore-lab/mindyolo/assets/91205957/081ca271-0b84-41e4-8f84-51affc4282a7)
，除此之外，我尝试过使用 ./demo/predict.py推理单张图片，结果是正常的，score能在0.8左右，而在result_dict的结果中，score都很小(<0.01),请问问题有可能出在哪呢

**Comment by zhanghuiyao** [comment]
如果infer结果正常，那很有可能是推理数据集的问题，image_id 应该是从 './coco/val2017.txt' 中取的，cocoeval接口的id是从 './coco/annotations/instances_val2017.json' 中取的，可以尝试检查下这两个文件是否是对齐的；
另外原test.py代码中会对判定为coco dataset的category_id做91to80的转换，这个地方注意一下；

**Comment by Versua0** [comment]
> 如果infer结果正常，那很有可能是推理数据集的问题，image_id 应该是从 './coco/val2017.txt' 中取的，cocoeval接口的id是从 './coco/annotations/instances_val2017.json' 中取的，可以尝试检查下这两个文件是否是对齐的;另外原test.py代码中会对判定为coco dataset的category_id做91to80的转换，这个地方注意一下；

感谢，问题都解决了，image_id出现问题是因为我们当初数据集是直接分割的，没有将文件名顺序改成从1开始，而代码应该是直接取图片文件名作为image_id.
然后全为0的原因是我们训练的方式是替换掉了原有分类中的类别，在保存结果的时候原代码中进行了80to90的转换，删去了这个步骤后，将预测出的类别加上1(80to90的转换对应为：0->1)就跟我们的类别id对应上了。

**Comment by zhanghuiyao** [comment]
congratulations

**Comment by southofwall** [comment]
> congratulations

您好，我在train.py文件让run_eval参数为True，在第一轮训练后评估时出现了以下问题，请问是那个环节出现了问题呢？
loading annotations into memory...
Done (t=0.10s)
creating index...
index created!
Loading and preparing results...
2023-08-06 16:25:49,797 [ERROR] pycocotools unable to run: list index out of range
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    train(args)
  File "train.py", line 282, in train
    ms_jit=args.ms_jit
  File "/home/ma-user/work/mindyolo-r0.3/mindyolo/utils/trainer_factory.py", line 205, in train
    self._on_train_epoch_end(run_context)
  File "/home/ma-user/work/mindyolo-r0.3/mindyolo/utils/trainer_factory.py", line 360, in _on_train_epoch_end
    cb.on_train_epoch_end(run_context)
  File "/home/ma-user/work/mindyolo-r0.3/mindyolo/utils/callback.py", line 255, in on_train_epoch_end
    self._run_eval(run_context)
  File "/home/ma-user/work/mindyolo-r0.3/mindyolo/utils/callback.py", line 287, in _run_eval
    accuracy = test_fn(network=eval_network)
  File "/home/ma-user/work/mindyolo-r0.3/test.py", line 200, in test
    raise e
  File "/home/ma-user/work/mindyolo-r0.3/test.py", line 190, in test
    pred = anno.loadRes(result_dicts)  # init predictions api
  File "/home/ma-user/modelarts-dev/common-algo-toolkit/pycocotools/coco.py", line 329, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range

**Comment by zhanghuiyao** [comment]
看起来是pycocotools接口调用的问题，可以尝试排查下result_dicts中的id的范围

**Comment by lonngxiang** [comment]
@zhanghuiyao   我这里运行test.py 报这错误是指？
![image](https://github.com/mindspore-lab/mindyolo/assets/40717349/354fe4bc-f363-4c55-be13-11b017bbc307)

**Comment by zhanghuiyao** [comment]
> @zhanghuiyao 我这里运行test.py 报这错误是指？自定义数据集没有annotations/instances_val2017.json这个 ![image](https://user-images.githubusercontent.com/40717349/282979282-354fe4bc-f363-4c55-be13-11b017bbc307.png)

test.py 运行的时候调用的是 pycocotools 的接口计算map，验证数据集需要是coco格式（包含这个json）

**Comment by zhanghuiyao** [comment]
> @zhanghuiyao 我这里运行test.py 报这错误是指？自定义数据集没有annotations/instances_val2017.json这个 ![image](https://user-images.githubusercontent.com/40717349/282979282-354fe4bc-f363-4c55-be13-11b017bbc307.png)

https://github.com/mindspore-lab/mindyolo/blob/master/examples/finetune_SHWD/convert_shwd2yolo.py#L258C45-L258C45

**Comment by lonngxiang** [comment]
> > @zhanghuiyao 我这里运行test.py 报这错误是指？自定义数据集没有annotations/instances_val2017.json这个 ![image](https://user-images.githubusercontent.com/40717349/282979282-354fe4bc-f363-4c55-be13-11b017bbc307.png)
> 
> 转换脚本可以参考这个 https://github.com/mindspore-lab/mindyolo/blob/master/examples/finetune_SHWD/convert_shwd2yolo.py#L258C45-L258C45

但我这个本身下载的就是yolov8格式的数据集，不用转换，但同时没有annotations/instances_val2017.json 文件，这种要怎么操作呢

**Comment by Ash-Lee233** [comment]
annotations一般是随数据集的，如果没有的话要自己手动标注

**Comment by Ash-Lee233** [comment]
问题单先关闭，如仍遇到问题可以提交新的issue或更改issue状态并提供相应信息
