### ISSUE TITLE
使用大图片出现问题

### ISSUE THREAD

**Issue by LeeLear** [mindspore-lab/mindyolo#187]
Corrupt JPEG data: 36 extraneous bytes before marker 0xd9
Corrupt JPEG data: 36 extraneous bytes before marker 0xd9
Corrupt JPEG data: 40 extraneous bytes before marker 0xd9
Corrupt JPEG data: 40 extraneous bytes before marker 0xd9
Corrupt JPEG data: 40 extraneous bytes before marker 0xd9
Corrupt JPEG data: 36 extraneous bytes before marker 0xd9
Corrupt JPEG data: 40 extraneous bytes before marker 0xd9
Corrupt JPEG data: 36 extraneous bytes before marker 0xd9
Corrupt JPEG data: 36 extraneous bytes before marker 0xd9
Corrupt JPEG data: 36 extraneous bytes before marker 0xd9
Corrupt JPEG data: 40 extraneous bytes before marker 0xd9
Corrupt JPEG data: 40 extraneous bytes before marker 0xd9
Corrupt JPEG data: 36 extraneous bytes before marker 0xd9
Corrupt JPEG data: 40 extraneous bytes before marker 0xd9
Corrupt JPEG data: 40 extraneous bytes before marker 0xd9
Corrupt JPEG data: 36 extraneous bytes before marker 0xd9
Corrupt JPEG data: 40 extraneous bytes before marker 0xd9

真实图片大小为 2500*1700 3240*2520等

**Comment by zhanghuiyao** [comment]
这个看起来是图片读取的时候就出现了问题
