### ISSUE TITLE
训练YOLOv7时报错“tuple index out of range”

### ISSUE THREAD

**Issue by RitzLu** [mindspore-lab/mindyolo#190]
### Hardware Environment(Ascend): 
Arm+D910B1

### Software Environment:
- **MindSpore 2.1.0**:
- **Python 3.7.10**:
- **EulerOS 2.0(SP10)**:

## Describe the current behavior
正常训练

## Describe the expected behavior
训练报错，报错信息：
![image](https://github.com/mindspore-lab/mindyolo/assets/22465325/3a81d99b-b50a-4c0e-a4da-0fa2cd4f1874)

## Steps to reproduce the issue
1. 执行训练命令 `python train.py --config ./configs/yolov7/yolov7.yaml`

**Comment by CaitinZhao** [comment]
目前MindSpore官方没有声称支持910B，如果想要使用的话，可以尝试配置环境变量

```
export MS_ENABLE_GE=1
export MS_GE_TRAIN=1
```

目前MindSpore在910B动静统一的支持有限，如果以上配置还是跑不通的话，只能等下个版本了
