### ISSUE TITLE
config文件中的参数与数据集加载类中的方法参数不一致

### ISSUE THREAD

**Issue by ruifenggong** [mindspore-lab/mindyolo#199]
yolov 8的配置参数：
`{func_name: mosaic, prob: 1.0, degrees: 0.0, translate: 0.1, scale: 0.9, shear: 0.0, copy_paste_prob: 0.3},`

https://github.com/mindspore-lab/mindyolo/blob/0313ab27ac87e0016108e9f9209df167266a132f/configs/yolov8/hyp.scratch.high.yaml#L31C3-L31C3

与dataset.py中的方法参数不对应，这个COCODataset真的能正确读取数据集吗？

https://github.com/mindspore-lab/mindyolo/blob/0313ab27ac87e0016108e9f9209df167266a132f/mindyolo/data/dataset.py#L341
`
    def mosaic(
        self,
        sample,
        mosaic9_prob=0.0,
    ):
`

**Comment by zhanghuiyao** [comment]
master 分支数据增强适配中，当前可以先用r0.2分支代码哈

**Comment by ruifenggong** [comment]
ok
