### ISSUE TITLE
master分支不对劲，yaml里的mosic参数和dataset中的都不一样

### ISSUE THREAD

**Issue by kill2013110** [mindspore-lab/mindyolo#201]
这master分支不对劲，yaml里的mosic参数和dataset中的都不一样

**Comment by kill2013110** [comment]
魔改了半天代码，结果发现这样

**Comment by kill2013110** [comment]
这各个分支到底是怎么用的

**Comment by kill2013110** [comment]
刚看了又好了，不知为何之前clone下来的代码不对劲

**Comment by zhanghuiyao** [comment]
master分支最近在做重构 新数据处理适配的pr刚合进去

**Comment by zhanghuiyao** [comment]
检测任务的稳定版本可以先用r0.2分支的

**Comment by kill2013110** [comment]
> 检测任务的稳定版本可以先用r0.2分支的

好的

**Comment by kill2013110** [comment]
> 检测任务的稳定版本可以先用r0.2分支的

r0.2支持mindspore2.0吗

**Comment by zhanghuiyao** [comment]
可以
r0.1 对应 mindspore 1.8.1/1.9
r0.2 对应 mindspore 2.0
master 对应 mindspore 2.0/2.1 (以README更新为准)

**Comment by kill2013110** [comment]
> 可以 r0.1 对应 mindspore 1.8.1/1.9 r0.2 对应 mindspore 2.0 master 对应 mindspore 2.0/2.1 (以README更新为准)

好的，谢谢辉耀哥，回复真快呐
