### ISSUE TITLE
mosiac和mixup 数据增强错误

### ISSUE THREAD

**Issue by guo-chengfeng** [mindspore-lab/mindyolo#202]
1 detect 任务但检测segments的类型, 使用yolo标注格式，没有segments，多处要检查segments
2 mosiac和mixup 传入了额外的参数
3 mosiac图片尺寸发生变化，640X640 变成 1280X1280，无法与没有数据增强的数据组成batch

**Comment by zhanghuiyao** [comment]
我们看下 master分支正在做数据重构，检测任务可以先用r0.2分支，这个问题我们看下

**Comment by guo-chengfeng** [comment]
这个问题，在今天最新的版本已经得到修复了。



在 2023-09-08 12:58:47，"zhanghuiyao" ***@***.***> 写道：

我们看下 master分支正在做数据重构，检测任务可以先用r0.2分支，这个问题我们看下

**Comment by zhanghuiyao** [comment]
> 1 detect 任务但检测segments的类型, 使用yolo标注格式，没有segments，多处要检查segments 2 mosiac和mixup 传入了额外的参数 3 mosiac图片尺寸发生变化，640X640 变成 1280X1280，无法与没有数据增强的数据组成batch

问题1和问题3都可以了吗

**Comment by guo-chengfeng** [comment]
问题1和问题3解决了

**Comment by zhanghuiyao** [comment]
问题二的数据适配已经在master合入了 后面可以尝试使用master的代码
