### ISSUE TITLE
训练精度问题

### ISSUE THREAD

**Issue by guo-chengfeng** [mindspore-lab/mindyolo#203]
V5 选择small的权重，loss一直为nan
V7 权重yolov7_300e_mAP508-734ac919.ckpt，loss一直为nan
V8 权重yolov8-n_500e_mAP372-cc07f5bd.ckpt， loss一直为10+，无法下降
相同的数据集，在pytorch版本中：
YOLOV5测试通过，能够正常训练
YOLOV8测试通过，能够正常训练

**Comment by zhanghuiyao** [comment]
你这边用的是什么设备 GPU还是Ascend

**Comment by guo-chengfeng** [comment]
使用的是GPU，现在测试的只有yolov7的tiny能正常训练。可能与设备有关。我试试Ascend



在 2023-09-08 13:00:14，"zhanghuiyao" ***@***.***> 写道：

你这边用的是什么设备 GPU还是Ascend

**Comment by zhanghuiyao** [comment]
当前release的模型都是在ascend上验证的，可以支持train/eval/predict；gpu上当前只支持 eval/predict；

**Comment by guo-chengfeng** [comment]
请问 mindyolo 支持 mindspore 1.10 版本吗？我尝试将其使用mindspore 1.10 运行 mindyolo, 但是失败了

**Comment by zhanghuiyao** [comment]
> 请问 mindyolo 支持 mindspore 1.10 版本吗？我尝试将其使用mindspore 1.10 运行 mindyolo, 但是失败了

可以试试 mindyolo r0.1 分支，r0.1本身可以支持1.8.1/1.9，1.10可能可以

**Comment by zoumaguanxin** [comment]
> 当前release的模型都是在ascend上验证的，可以支持train/eval/predict；gpu上当前只支持 eval/predict；

在gpu上试了下训练yolov3，loss不高，但是也不降。跑了一百个epoch,predict一张训练集数据，结果空空如也。
