### ISSUE TITLE
 from mindyolo.utils.config import parse_config 没有parse_config函数

### ISSUE THREAD

**Issue by guo-chengfeng** [mindspore-lab/mindyolo#204]
几乎每个mindyolo/models/下的模型定义都有如下的测试，但是parse_config根本不存在
if __name__ == "__main__":
    from mindyolo.models.model_factory import create_model
    from mindyolo.utils.config import parse_config

**Comment by zhanghuiyao** [comment]
之前改写法的时候把这个地方漏了 感谢指正 我们改下
