### ISSUE TITLE
r0.1分支 加载预训练模型strict_load=False配置不起作用

### ISSUE THREAD

**Issue by ruifenggong** [mindspore-lab/mindyolo#206]
在加载coco预训练模型用于微调时，参考了master分支的example里面的readme，有提到使用strict_load=False去掉类别不匹配导致的问题
https://github.com/mindspore-lab/mindyolo/blob/9ac823d0184253bd651faa65d9cbaa0615cb8e6b/examples/finetune_SHWD/yolov7-tiny_shwd.yaml#L8

但在r0.1分支，该参数并不存在，这令人困惑

https://github.com/mindspore-lab/mindyolo/blob/7f857ef07c7327a5c4b13515b9a907bdb3e00d42/train.py#L128

https://github.com/mindspore-lab/mindyolo/blob/7f857ef07c7327a5c4b13515b9a907bdb3e00d42/mindyolo/utils/utils.py#L88

因为当前使用的算力中心尚不支持mindspore2.0，因而使用mindspore1.10.1的版本，这个特性是否还会加入到r0.1分支？

**Comment by zhanghuiyao** [comment]
这个修改不会合入到r0.1，可以尝试参考如下pr增加这个功能
https://github.com/mindspore-lab/mindyolo/pull/181
