### ISSUE TITLE
tests/dataset_plots.py的代码能用吗，为啥一堆bug？

### ISSUE THREAD

**Issue by kill2013110** [mindspore-lab/mindyolo#207]
r0.2版本，GPU

**Comment by zhanghuiyao** [comment]
报错信息可以贴一下

**Comment by kill2013110** [comment]
yolov8m，首先是cfg = parse_args("eval")，这行跑不通。然后我把tests中的parse部分代码移过来，跑通发现画图的时候img shape还是（3,640,640），得transpose。而且labels中的box竟然是归一化的，所以模型计算损失的时候也是利用归一化后的标签计算的吗？这个跟常见的yolo实现都不太一样

**Comment by kill2013110** [comment]
> yolov8m，首先是cfg = parse_args("eval")，这行跑不通。然后我把tests中的parse部分代码移过来，跑通发现画图的时候img shape还是（3,640,640），得transpose。而且labels中的box竟然是归一化的，所以模型计算损失的时候也是利用归一化后的标签计算的吗？这个跟常见的yolo实现都不太一样

归一化就是label_norm这个transforms，这一步是干啥的？yolo原始就是norm的标签，加载的时候转成绝对标签了，现在又转成norm的了

**Comment by yuedongli1** [comment]
代码更新时这个地方忘记适配了，目前整改中

**Comment by kill2013110** [comment]
master分支现在能用吗

**Comment by kill2013110** [comment]
> > yolov8m，首先是cfg = parse_args("eval")，这行跑不通。然后我把tests中的parse部分代码移过来，跑通发现画图的时候img shape还是（3,640,640），得transpose。而且labels中的box竟然是归一化的，所以模型计算损失的时候也是利用归一化后的标签计算的吗？这个跟常见的yolo实现都不太一样
> 
> 归一化就是label_norm这个transforms，这一步是干啥的？yolo原始就是norm的标签，加载的时候转成绝对标签了，现在又转成norm的了

看了下loss的代码，又转回绝对坐标target了

**Comment by zhanghuiyao** [comment]
> > yolov8m，首先是cfg = parse_args("eval")，这行跑不通。然后我把tests中的parse部分代码移过来，跑通发现画图的时候img shape还是（3,640,640），得transpose。而且labels中的box竟然是归一化的，所以模型计算损失的时候也是利用归一化后的标签计算的吗？这个跟常见的yolo实现都不太一样
> 
> 归一化就是label_norm这个transforms，这一步是干啥的？yolo原始就是norm的标签，加载的时候转成绝对标签了，现在又转成norm的了

网络计算loss前先对boxes做了normlize的操作，这个操作是否需要具体看loss的定义，当前库上预置的loss都是用的归一化后的label计算的

**Comment by zhanghuiyao** [comment]
可视化的代码合进去了 可以试下最新的看看还有没有问题
