### ISSUE TITLE
转换air模型报错

### ISSUE THREAD

**Issue by Joe-bit-create** [mindspore-lab/mindyolo#210]
执行命令：

<img width="485" alt="image" src="https://github.com/mindspore-lab/mindyolo/assets/58928331/e19f0b3c-0af6-4e10-a856-f30c00be124f">

报错：

<img width="486" alt="image" src="https://github.com/mindspore-lab/mindyolo/assets/58928331/142e56c9-2cd1-4690-9a36-16ad90f2ac90">

**Comment by zhanghuiyao** [comment]
910A导出是没问题的，910B的我们看下

**Comment by zhanghuiyao** [comment]
lite export当前只支持910A，910B上还未适配
