### ISSUE TITLE
metrics.py中clip函数非原地操作，需要有返回值

### ISSUE THREAD

**Issue by chengtianwu** [mindspore-lab/mindyolo#218]
https://github.com/mindspore-lab/mindyolo/blob/f8bd518c2e1860f243d99c20e2a1989aed9cb7e3/mindyolo/utils/metrics.py#L152
https://github.com/mindspore-lab/mindyolo/blob/f8bd518c2e1860f243d99c20e2a1989aed9cb7e3/test.py#L344C13-L344C25
函数本身和函数调用的地方都需要改

**Comment by Ash-Lee233** [comment]
感谢提问，请问您有修改意见吗？

**Comment by chengtianwu** [comment]
> 感谢提问，请问您有修改意见吗？

把返回值加上就好了

**Comment by Ash-Lee233** [comment]
函数里有return boxes的，能给个具体的修改意见吗？主要是没太明白您想要的结果，感谢
