### ISSUE TITLE
有没有docker镜像呀，依赖环境一堆报错，直接像mindone一样的镜像一键就能跑通

### ISSUE THREAD

**Issue by zainlau** [mindspore-lab/mindyolo#222]
参考武汉AICC的镜像仓库

**Comment by zhanghuiyao** [comment]
环境建议可以尝试根据 [Installation](https://github.com/mindspore-lab/mindyolo/blob/master/docs/en/installation.md) 文档进行环境配置

**Comment by zainlau** [comment]
可以在310上跑推理吗

**Comment by zhanghuiyao** [comment]
可以的 参考 [depoly](https://github.com/mindspore-lab/mindyolo/tree/master/deploy) 部分
