### ISSUE TITLE
torch_npu包的安装问题

### ISSUE THREAD

**Issue by zainlau** [mindspore-lab/mindyolo#224]
根据官网和博客上很多教程操作了一遍，都没解决；
为什么一个pip install就能解决的问题，非要搞一堆莫名其妙的问题

**Comment by zainlau** [comment]
310P

**Comment by zhanghuiyao** [comment]
torch npu包没装过，可以尝试在 gitee 社区上提个issue问下
https://gitee.com/ascend/pytorch
