### ISSUE TITLE
自定义数据集训练出错

### ISSUE THREAD

**Issue by liuxy2318** [mindspore-lab/mindyolo#227]
训练环境：Ascend910 mindspore2.0.0
报错信息：invalid literal for int() with base 10: '0000f77c-6257be58'
![image](https://github.com/mindspore-lab/mindyolo/assets/65705604/2820ed19-e1a5-439b-8b5f-97d907dd0218)
数据格式是coco格式的：
![image](https://github.com/mindspore-lab/mindyolo/assets/65705604/3f7064f3-4f8f-48d1-97d6-6d8bf0ed9aa0)
![image](https://github.com/mindspore-lab/mindyolo/assets/65705604/a393c004-a080-4d12-9a25-f78da6c389a4)
希望可以帮忙解答一下，是哪里的问题？

**Comment by zhanghuiyao** [comment]
看起来应该是文件名中包含其他字符导致转int类型失败，建议可以尝试 dataset.py 代码逻辑适应自定义数据集 或 修改数据集的文件名只包含数字；

**Comment by lonngxiang** [comment]
> 看起来应该是文件名中包含其他字符导致转int类型失败，建议可以尝试 dataset.py 代码逻辑适应自定义数据集 或 修改数据集的文件名只包含数字；

也报相同错误，没大理解，怎么修改呢
![image](https://github.com/mindspore-lab/mindyolo/assets/40717349/f8a9f54c-5c2f-4f86-8a08-579ae9eb7cba)

**Comment by zhanghuiyao** [comment]
> > 看起来应该是文件名中包含其他字符导致转int类型失败，建议可以尝试 dataset.py 代码逻辑适应自定义数据集 或 修改数据集的文件名只包含数字；
> 
> 也报相同错误，没大理解，怎么修改呢 

直接修改自定义数据集的文件名 或者 改数据读取的逻辑

**Comment by lonngxiang** [comment]
> > > 看起来应该是文件名中包含其他字符导致转int类型失败，建议可以尝试 dataset.py 代码逻辑适应自定义数据集 或 修改数据集的文件名只包含数字；
> > 
> > 
> > 也报相同错误，没大理解，怎么修改呢
> 
> 直接修改自定义数据集的文件名 或者 改数据读取的逻辑

直接修改自定义数据集的文件名是指train里面每张图片的名称前缀吗

**Comment by Ash-Lee233** [comment]
问题单先关闭，如仍遇到问题可以提交新的issue或更改issue状态并提供相应信息
