### ISSUE TITLE
AIcore利用率为0

### ISSUE THREAD

**Issue by zainlau** [mindspore-lab/mindyolo#228]
HBM利用率是正常的，只有AIcore利用率为0

**Comment by zhanghuiyao** [comment]
什么模型 什么场景？

**Comment by zainlau** [comment]
> 什么模型 什么场景？

yolov5s,coco128,训练，目标检测，用的官方镜像，环境应该没问题

**Comment by zhanghuiyao** [comment]
是否有报错 第一个loss可以正常打印出来吗？

**Comment by zainlau** [comment]
> 是否有报错 第一个loss可以正常打印出来吗？

没报错，可以打印loss，就是AIcore没起来，好像从头到尾都是AICPU在跑

**Comment by zhanghuiyao** [comment]
估计是显示的问题，云的话可以截图在云的社区上提个工单
