### ISSUE TITLE
转onnx后运行deploy/predict.py推理结果不正确

### ISSUE THREAD

**Issue by zoumaguanxin** [mindspore-lab/mindyolo#230]
### 测试环境
```
docker pull zoumaguanxin/mindyolo:mindsporegpu-2.1.1
```
克隆mindyolo库，在容器中进行测试。

### 测试过程
从官方网站下在了yolov8m的模型，直接运行如下命令，结果正确
```
python demo/predict.py --config ./configs/yolov8/yolov8m.yaml --weight=weights/yolov8-m_500e_mAP505-8ff7a728.ckpt --image_
path data/bus.jpg  --device_target=GPU
```
![bus](https://github.com/mindspore-lab/mindyolo/assets/22088579/878f635e-b628-4b77-92b5-9aa2757df685)

然后先将代码中conv.py中的nn.SiLU替换为EdgeSiLU
```python
class EdgeSiLU(nn.Cell):
    """
    SiLU activation function: x * sigmoid(x). To support for onnx export with nn.SiLU.
    """

    def __init__(self):
        super().__init__()

    def construct(self, x):
        return x * ops.sigmoid(x)
```
采用如下命令转换为onnx
```python
python ./deploy/export.py --config ./configs/yolov8/yolov8m.yaml --weight ./weights/yolov8-m_500e_mAP505-8ff7a728.ckpt --per_batch_size 1 --file_format ONNX --device_target CPU
```

然后运行如下命令，出来的结果不正确
```
python deploy/predict.py --model_type ONNX --model_path yolov8m.onnx --config ./configs/yolov8/yolov8m.yaml --image_path ./data/bus.jpg --device_target CPU
```

![bus](https://github.com/mindspore-lab/mindyolo/assets/22088579/7c71094d-c9e2-4838-adf9-97a350444874)

**Comment by zhanghuiyao** [comment]
@ltcs11

**Comment by zhanghuiyao** [comment]
onnx推理当前还不支持，只有部分实验性的场景适用，见 [这里](https://github.com/mindspore-lab/mindyolo/blob/master/deploy/ONNX.md)，这个看起来有可能是模型转换过程中出现的精度误差，固定模型的输入对比下转换前后模型的输出是不是一样的

**Comment by ltcs11** [comment]
测试了一下MindIR格式可以正常infer，应该是mindspore自身在导出模型时出现的精度问题

**Comment by zoumaguanxin** [comment]
测试了yolov3没问题，yolov8m不得行

**Comment by zoumaguanxin** [comment]
> 测试了一下MindIR格式可以正常infer，应该是mindspore自身在导出模型时出现的精度问题

测试了yolov3确实能跑通上面流程，yolov8m不得行

**Comment by zhanghuiyao** [comment]
> > 测试了一下MindIR格式可以正常infer，应该是mindspore自身在导出模型时出现的精度问题
> 
> 测试了yolov3确实能跑通上面流程，yolov8m不得行

看起来是onnx导出的模型有精度误差，可以尝试固定输入权重确认这个误差，然后在 gitee mindspore 仓库上提交issue来推动框架修复这个bug；
