### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lonngxiang** [mindspore-lab/mindyolo#232]
![image](https://github.com/mindspore-lab/mindyolo/assets/40717349/25e2cd47-b717-4305-862e-e11c1a2f221b)

**Comment by zhanghuiyao** [comment]
Looks like the OpenCV version is incompatible

**Comment by qianheee** [comment]
有两个版本有问题才会造成这个问题，将这两个你原来版本卸载，安装这两个版本opencv-python 4.7.0.68，opencv-python-headless 4.7.0.68，你的问题就会解决

**Comment by lonngxiang** [comment]
安装了还是不行

![image](https://github.com/mindspore-lab/mindyolo/assets/40717349/20289948-44cb-43f2-a5f9-0f200fdd338a)

![image](https://github.com/mindspore-lab/mindyolo/assets/40717349/4fd84229-146c-4f06-a8d7-8127e05d7b71)


> 有两个版本有问题才会造成这个问题，将这两个你原来版本卸载，安装这两个版本opencv-python 4.7.0.68，opencv-python-headless 4.7.0.68，你的问题就会解决

**Comment by qianheee** [comment]
https://github.com/mindspore-lab/mindyolo/blob/master/docs/en/installation.md你看一下，你把这些安装步骤都走完了吗

**Comment by lonngxiang** [comment]
> https://github.com/mindspore-lab/mindyolo/blob/master/docs/en/installation.md
安装说明安装好对应版本，运行也还是报上面错误
![image](https://github.com/mindspore-lab/mindyolo/assets/40717349/6f043f8e-db26-4638-b03c-f11c2937e1a6)

**Comment by zhanghuiyao** [comment]
可以尝试下安装这个文件看看

**Comment by lonngxiang** [comment]
> opencv-python==4.8.1.78
多谢，这个组合能运行，两者都需要
![image](https://github.com/mindspore-lab/mindyolo/assets/40717349/db3c76d1-dba6-42b3-af22-5aa4f0d72027)
