### ISSUE TITLE
yolov5

### ISSUE THREAD

**Issue by qianheee** [mindspore-lab/mindyolo#234]
运行python train.py --config ./configs/yolov5/yolov5n.yaml显示package not installed, albumentations load failed，但是已经下载了这个包，这样要怎么办

**Comment by zhanghuiyao** [comment]
这个提示应该是 albumentations 包没有正确安装，可以尝试用pip装一下

**Comment by iamzjs** [comment]
先进入代码根目录，然后执行以下两条，应该就可以了。
pip install -r requirements.txt
pip install -e .
