### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../../coco.yaml

### ISSUE THREAD

**Issue by lonngxiang** [mindspore-lab/mindyolo#235]
运行报错
python demo/predict.py --config ../yolov7-tiny.yaml --weight=../yolov7-tiny_300e_mAP375-d8972c94.ckpt --image_path ../kk1.jpg

![image](https://github.com/mindspore-lab/mindyolo/assets/40717349/0c03cb9f-90cf-41a6-93a4-8358940e6858)

**Comment by lonngxiang** [comment]
看案例，没有说还需要下载coco.yaml呀 

https://github.com/mindspore-lab/mindyolo/blob/master/GETTING_STARTED.md

**Comment by zhanghuiyao** [comment]
coco.yaml 不用另外下载，在代码 config/coco.yaml 中，看上面的报错应该是路径不对导致访问不到这个文件，可以尝试把当前路径放到pythonpath中
export PYTHONPATH=/path to/mindyolo/

**Comment by lonngxiang** [comment]
> coco.yaml 不用另外下载，在代码 config/coco.yaml 中，看上面的报错应该是路径不对导致访问不到这个文件，可以尝试把当前路径放到pythonpath中 export PYTHONPATH=/path to/mindyolo/

嗯嗯，我大概明白了，原来是模型不用单独下载，/configs/yolov7/下面直接有
