### ISSUE TITLE
自定义训练数据，指定加载多份yaml文件，nc到底是以哪个为准？

### ISSUE THREAD

**Issue by lonngxiang** [mindspore-lab/mindyolo#237]
比如运行：python train.py --config ./configs/yolov8/yolov8n.yaml --device_target Ascend
里面包括：其中 '../coco.yaml',  './yolov8-base.yaml'两个里面都有nc lables定义，到底是以谁为准呢
![image](https://github.com/mindspore-lab/mindyolo/assets/40717349/6dce0daa-04e5-4e4f-92ea-965d636299b7)

**Comment by zhanghuiyao** [comment]
逐级覆盖，所有可配置参数满足，命令行直接传入 > yolov8n.yaml > yolov8-base.yaml > hyp.yaml > coco.yaml

**Comment by lonngxiang** [comment]
> 逐级覆盖，所有可配置参数满足，命令行直接传入 > yolov8n.yaml > yolov8-base.yaml > hyp.yaml > coco.yaml

那我这边coco.yaml上传了比如5， yolov8-base.yaml 默认是80，但运行训练正常没有报错，那怕这样也算有问题把，训练与实际想训练的lables 5不一致
![image](https://github.com/mindspore-lab/mindyolo/assets/40717349/632a732e-39b6-4f07-899b-910e6849fced)

**Comment by lonngxiang** [comment]
> 逐级覆盖，所有可配置参数满足，命令行直接传入 > yolov8n.yaml > yolov8-base.yaml > hyp.yaml > coco.yaml

names 这些指标也是这个顺序吗

**Comment by zhanghuiyao** [comment]
是的 所有可配置参数都满足，可以理解为“参数继承”

**Comment by lonngxiang** [comment]
嗯，我这里更改  yolov8-base.yaml里epochs: 500 改成100；运行的时候报错；500这里不是已经修改了吗怎么这里还有

![image](https://github.com/mindspore-lab/mindyolo/assets/40717349/3c4b5377-6c1e-446b-90f5-0bafd81aa3a3)

**Comment by lonngxiang** [comment]
> 是的 所有可配置参数都满足，可以理解为“参数继承”

运行还发现个问题，如果参数不是在 yolov8-base.yaml里指定，写在其他比如coco.yaml，训练的时候过程中不会答应coco.yaml定义的nc ，names这些重要的值

![image](https://github.com/mindspore-lab/mindyolo/assets/40717349/950e4ffd-a52b-4e70-8824-69fa978fb64c)

**Comment by zhanghuiyao** [comment]
> 嗯，我这里更改 yolov8-base.yaml里epochs: 500 改成100；运行的时候报错；500这里不是已经修改了吗怎么这里还有
> 
> ![image](https://user-images.githubusercontent.com/40717349/282685280-3c4b5377-6c1e-446b-90f5-0bafd81aa3a3.png)

这个报错应该是配置了两阶段数据集训练，修改整体训练epoch需要和数据相匹配，单阶段训练不用

**Comment by zhanghuiyao** [comment]
> > 是的 所有可配置参数都满足，可以理解为“参数继承”
> 
> 运行还发现个问题，如果参数不是在 yolov8-base.yaml里指定，写在其他比如coco.yaml，训练的时候过程中不会打印coco.yaml定义的nc ，names这些重要的值
> 
> ![image](https://user-images.githubusercontent.com/40717349/282685572-950e4ffd-a52b-4e70-8824-69fa978fb64c.png)

理论上应该是会打印的 这个截图是所有的打印日志吗？

**Comment by lonngxiang** [comment]
> python train.py --config ./configs/yolov8/yolov8n.yaml --device_target Ascend

不是，就是运行python train.py --config ./configs/yolov8/yolov8n.yaml --device_target Ascend的日志

**Comment by lonngxiang** [comment]
> > 嗯，我这里更改 yolov8-base.yaml里epochs: 500 改成100；运行的时候报错；500这里不是已经修改了吗怎么这里还有
> > ![image](https://user-images.githubusercontent.com/40717349/282685280-3c4b5377-6c1e-446b-90f5-0bafd81aa3a3.png)
> 
> 这个报错应该是配置了两阶段数据集训练，修改整体训练epoch需要和数据相匹配，单阶段训练不用

两阶段数据集训练 这是什么意思呢，那这个问题需要怎么修改呢，改成单阶段训练

**Comment by zhanghuiyao** [comment]
以 yolov8n 为例，如果你要跑100个epoch，需要在数据定义的地方同步修改
https://github.com/mindspore-lab/mindyolo/blob/master/configs/yolov8/hyp.scratch.low.yaml#L30

**Comment by lonngxiang** [comment]
> 以 yolov8n 为例，如果你要跑100个epoch，需要在数据定义的地方同步修改 https://github.com/mindspore-lab/mindyolo/blob/master/configs/yolov8/hyp.scratch.low.yaml#L30 <img alt="image" width="603" src="https://user-images.githubusercontent.com/20476835/282992054-1c9bea36-aca2-4a32-8eb8-8d19f64faa3e.png">

比如100个epoch，这两者数据不同增强方式自己看着调整比例就行吗，比如[90,10],[20,80],还是说一般前者大些比较好

**Comment by Ash-Lee233** [comment]
超参数需要根据不同的数据集调整

**Comment by Ash-Lee233** [comment]
问题单先关闭，如仍遇到问题可以提交新的issue或更改issue状态并提供相应信息
