### ISSUE TITLE
在310B上MindX推理报错AttributeError: 'COCODataset' object has no attribute 'column_names_getitem'

### ISSUE THREAD

**Issue by langshhhh** [mindspore-lab/mindyolo#239]
测试环境：
cann6.2.rc2  python3.9.2  mindxsdk 5.0.rc2 
测试方式：
从官方网站下在了yolov8m的模型，直接运行如下命令，
 python ./deploy/test.py --model_type MindX --model_path /root/yolo.om --config ./configs/yolov8/yolov8n.yaml
报错AttributeError: 'COCODataset' object has no attribute 'column_names_getitem'
数据集使用的是coco数据集

**Comment by zhanghuiyao** [comment]
看mindyolo r0.2/master 代码是有这个属性的，看看环境中是否有安装了mindyolo 0.1或有PATH指向了其他包

**Comment by langshhhh** [comment]
装了mindyolo 0.2  只配置了cann的变量  没有其他PATH了

**Comment by zhanghuiyao** [comment]
看起来还是没找到这个属性，可以在代码运行的地方打一下断点，看看是不是用到了当前目录下的COCODataset

**Comment by langshhhh** [comment]
之前 翻了代码 是有这个属性  但就是找不到不知道为什么

**Comment by langshhhh** [comment]
结束
