### ISSUE TITLE
推理有更简单的命令方式吗？

### ISSUE THREAD

**Issue by lonngxiang** [mindspore-lab/mindyolo#240]
只能是这种安装MindSpore Lite去推理吗？
`python ./deploy/export.py --config ./configs/yolov5/yolov5n.yaml --weight yolov5n_300e_mAP273-9b16bd7b.ckpt --per_batch_size 1 --file_format MINDIR --device_target Ascend
`
https://mindspore-lab.github.io/mindyolo/zh/tutorials/deployment/

**Comment by zhanghuiyao** [comment]
这个是离线推理的导出过程

> 只能是这种安装MindSpore Lite去推理吗？ `python ./deploy/export.py --config ./configs/yolov5/yolov5n.yaml --weight yolov5n_300e_mAP273-9b16bd7b.ckpt --per_batch_size 1 --file_format MINDIR --device_target Ascend ` https://mindspore-lab.github.io/mindyolo/zh/tutorials/deployment/

**Comment by zhanghuiyao** [comment]
在线推理可以参考 [getting_started](https://github.com/mindspore-lab/mindyolo/blob/master/GETTING_STARTED.md)
离线推理可以参考 [depoly](https://github.com/mindspore-lab/mindyolo/blob/master/deploy/README.md)
