### ISSUE TITLE
mindyolo只支持训练coco数据集格式吗

### ISSUE THREAD

**Issue by lonngxiang** [mindspore-lab/mindyolo#241]
其他voc、yolo数据集格式支持吗

**Comment by zhanghuiyao** [comment]
当前暂时只支持 yolo 格式，其他自定义数据集可以尝试转成yolo格式跑

**Comment by zhanghuiyao** [comment]
自定义数据集可以参考这个
https://github.com/mindspore-lab/mindyolo/tree/master/examples/finetune_SHWD

**Comment by lonngxiang** [comment]
> 当前暂时只支持 yolo 格式，其他自定义数据集可以尝试转成yolo格式跑

既然是yolo格式，就是奇怪run test.py 报错 是缺失voc格式的json文件

**Comment by zhanghuiyao** [comment]
> > 当前暂时只支持 yolo 格式，其他自定义数据集可以尝试转成yolo格式跑
> 
> 既然是yolo格式，就是奇怪run test.py 报错 是缺失voc格式的json文件

test.py 缺失的json是coco格式的
