### ISSUE TITLE
在310B上MindX推理单张图片报错

### ISSUE THREAD

**Issue by langshhhh** [mindspore-lab/mindyolo#243]
测试环境：
cann6.2.rc2 python3.9.2 mindxsdk 5.0.rc2
测试方式：
从官方网站下在了yolov8m的模型，直接运行如下命令，
python ./deploy/predict.py --model_type MindX --model_path /root/yolo.om --config  ./configs/yolov8/yolov8n.yaml --image_path ./coco/images/val2017/000000103585.jpg
报错：
Begin to initialize Log.
The output directory of logs file exist.
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20231116 09:50:40.316920  2326 FileUtils.cpp:330] The input file is empty
I20231116 09:50:40.316954  2326 FileUtils.cpp:472] Check Other group permission: Current permission is 4, but required no greater than 0.
Save logs information to specified directory.
E20231116 09:50:41.157967  2326 MxOmModelDesc.cpp:855] [507011][Error code unknown] Failed to model infer execute, details seen in CANN document.
E20231116 09:50:41.158447  2326 MxOmModelDesc.cpp:129] Model Infer failed.
E20231116 09:50:41.158478  2326 MxOmModelDesc.cpp:154] Infer failed, result is null
Traceback (most recent call last):
  File "/root/mindyolo/./deploy/predict.py", line 217, in <module>
    infer(args)
  File "/root/mindyolo/./deploy/predict.py", line 195, in infer
    result_dict = detect(
  File "/root/mindyolo/./deploy/predict.py", line 116, in detect
    out = network.infer(img)[0]  # inference and training outputs
IndexError: list index out of range

数据集使用的是coco数据集

NPU卡信息：
+--------------------------------------------------------------------------------------------------------+
| npu-smi 23.0.rc1.1                               Version: 23.0.rc1.1                                   |
+-------------------------------+-----------------+------------------------------------------------------+
| NPU     Name                  | Health          | Power(W)     Temp(C)           Hugepages-Usage(page) |
| Chip    Device                | Bus-Id          | AICore(%)    Memory-Usage(MB)                        |
+===============================+=================+======================================================+
| 0       310B                  | OK              | 8.7          41                15    / 1400          |
| 0       0                     | NA              | 0            5695 / 11578                            |
+===============================+=================+======================================================+

**Comment by HanxiXiao** [comment]
这个问题是怎么解决的呢

**Comment by langshhhh** [comment]
> 这个问题是怎么解决的呢

修改了一下权限 改成600就好了
