### ISSUE TITLE
在win64环境下推理yolo5报错ImportError: cannot import name 'process_mask_upsample' from 'mindyolo.utils.metrics'

### ISSUE THREAD

**Issue by luoliou** [mindspore-lab/mindyolo#246]
![Snipaste_2023-11-22_21-29-29](https://github.com/mindspore-lab/mindyolo/assets/53136267/a92198e4-ca6b-4089-bde9-f077a89c6c47)
在win64环境下推理yolo5报错ImportError: cannot import name 'process_mask_upsample' from 'mindyolo.utils.metrics'
环境：
mindspore：2.1
python：3.7.10
操作系统：win11

执行的命令：
`python demo/predict.py --config ./configs/yolov5/yolov5s.yaml --weight=/path_to_ckpt/yolov5s_300e_mAP376-860bcf3b.ckpt --image_path /path_to_image/dog.jpg --device_target=CPU`

**Comment by zhanghuiyao** [comment]
看报错是没找到这个接口，像是pythonpath路径的问题
