### ISSUE TITLE
在昇腾910A环境下推理yolo5报错：AttributeError: module 'mindspore' has no attribute 'jit'

### ISSUE THREAD

**Issue by luoliou** [mindspore-lab/mindyolo#247]
### 环境
mindspore:1.8.1
python:3.7.10
操作系统：EulerOS 2.0 (SP8), CANN-5.1.RC2.1
### 报错信息
![Snipaste_2023-11-22_21-47-11](https://github.com/mindspore-lab/mindyolo/assets/53136267/034ed1c7-ec7a-4f38-b96f-ce305739bacf)
### 代码
`python demo/predict.py --config ./configs/yolov5/yolov5s.yaml --weight=/path_to_ckpt/yolov5s_300e_mAP376-860bcf3b.ckpt --image_path /path_to_image/bus.jpg`

不知道mindyolo对mindspore版本是否有要求，版本必须大于2.0吗？

**Comment by zhanghuiyao** [comment]
这个看起来是MindSpore1.8.1里面没有jit接口，master分支可以尝试在MindSpore 2.0/2.1上跑，版本可以版本依赖可以参考这个
https://github.com/mindspore-lab/mindyolo/blob/master/docs/en/installation.md
