### ISSUE TITLE
MindYolo 执行单张图片推理报错

### ISSUE THREAD

**Issue by ermao1577973673** [mindspore-lab/mindyolo#249]
环境信息：
CANN-6.3.RC2
Mindspore 2.1.1
Mindspore-lite 2.0.0a0

操作参考文档：
https://github.com/mindspore-lab/mindyolo/tree/master/deploy 

执行单张图片推理和COCO数据集推理都报错，报错信息如下：

Traceback (most recent call last):
  File "deploy/predict.py", line 217, in <module>
    [infer(args)](url)
  File "deploy/predict.py", line 174, in infer
    network = LiteModel(args.model_path)
  File "/home/mindyolo/deploy/infer_engine/lite.py", line 12, in __init__
    self._init_model()
  File "/home/mindyolo/deploy/infer_engine/lite.py", line 15, in _init_model
    import mindspore_lite as mslite
  File "/root/anaconda3/envs/mindspore-lite/lib/python3.7/site-packages/mindspore_lite/__init__.py", line 19, in <module>
    from .context import Context, DeviceInfo, CPUDeviceInfo, GPUDeviceInfo, AscendDeviceInfo
  File "/root/anaconda3/envs/mindspore-lite/lib/python3.7/site-packages/mindspore_lite/context.py", line 19, in <module>
    from .lib import _c_lite_wrapper
ImportError: /root/anaconda3/envs/mindspore-lite/lib/python3.7/site-packages/mindspore_lite/lib/libmindspore_converter.so: undefined symbol: _ZTVN9mindspore12TypeAnythingE

另：文档写的太粗糙，按照文档操作，会报各种少包问题，还有CANN版本不i安荣问题，最终还是跑不通；不知道作者自己跑了没有，为什么不给出自己的详细配置信息

**Comment by zhanghuiyao** [comment]
这个看起来是环境配置的问题，Mindspore-lite 2.0.0a0配套cann版本可以参考 [官网](https://www.mindspore.cn/versions)
<img width="1206" alt="image" src="https://github.com/mindspore-lab/mindyolo/assets/20476835/3416e9fa-3c5c-4b9f-85cd-ba508f9a901c">

**Comment by iamzjs** [comment]
910下，单张图片不使用lite，model_type设置为MindIR是可以推理的，使用Lite报错。
python ./deploy/predict.py --model_type MindIR --model_path ./yolov5n.mindir --config ./configs/yolov5/yolov5n.yaml --save_result True --image_path ./coco/images/val2017/000000118921.jpg

**Comment by zhanghuiyao** [comment]
> 910下，单张图片不使用lite，model_type设置为MindIR是可以推理的，使用Lite报错。 python ./deploy/predict.py --model_type MindIR --model_path ./yolov5n.mindir --config ./configs/yolov5/yolov5n.yaml --save_result True --image_path ./coco/images/val2017/000000118921.jpg

那估计是lite的bug，可以另外提个issue贴一下报错
