### ISSUE TITLE
RuntimeError: The device address type is wrong: type name in address:CPU, type name in context:Ascend

### ISSUE THREAD

**Issue by lyman-meng** [mindspore-lab/mindyolo#251]
您好，麻烦帮看下这个问题
![image](https://github.com/mindspore-lab/mindyolo/assets/31296804/ab0a4fd2-aaa1-4a4d-a951-6a1a70297d13)
RuntimeError: The device address type is wrong: type name in address:CPU, type name in context:Ascend

CANN：7.0.RC1
MindSpore2.1.0
Ascend310

**Comment by zhanghuiyao** [comment]
看起来像是环境的问题 可以尝试按照 [lite readme](https://github.com/mindspore-lab/mindyolo/blob/master/deploy/README.md) 配置下环境，安装见[MindSpore官网](https://www.mindspore.cn/install)

**Comment by gyy8426** [comment]
我也出现了这个问题请问解决了么？
