### ISSUE TITLE
Training process is suddenly killed

### ISSUE THREAD

**Issue by jb2849** [mindspore-lab/mindyolo#254]
I am trying to train my model on my computer with RTX3060. However, the training process was killed frequently. Would you mind help me with that issue
![image](https://github.com/mindspore-lab/mindyolo/assets/22161136/a88672ca-3608-4150-ad11-58a270aedc83)
?

**Comment by zhanghuiyao** [comment]
It seems that the system killed your process, and it may have something to do with the CPU and memory configuration, you can try running a minimal network
