### ISSUE TITLE
YOLOV7模型的权重与所提供的config的并不一致，无法加载

### ISSUE THREAD

**Issue by Singerone** [mindspore-lab/mindyolo#265]
模型权重从所提供的model_zoo中直接下载，config也是对应modelzoo中所提供的配置文件内容。
训练指令：
mindyolo-master/train.py --config /code/mindyolo-master/configs/yolov7/yolov7.yaml  --weight /code/mindyolo-master/pretrain/yolov7_300e_mAP508-734ac919.ckpt

存在报错：
RuntimeError: For 'load_param_into_net', model.model.105.m.0.weight in the argument 'net' should have the same shape as model.model.105.m.0.weight in the argument 'parameter_dict'. But got its shape (45, 256, 1, 1) in the argument 'net' and shape (255, 256, 1, 1) in the argument 'parameter_dict'.May you need to check whether the checkpoint you loaded is correct or the batch size and so on in the 'net' and 'parameter_dict' are same.
![image](https://github.com/mindspore-lab/mindyolo/assets/51075561/26d86780-6977-4464-8d6f-8fefc05dd920)

**Comment by liuwake** [comment]
早cofig文件中增加`strict_load: False`即可
