### ISSUE TITLE
yolov5m 8卡 可以拉起训练 显存有占用 但是aicore使用率为0

### ISSUE THREAD

**Issue by Walker-yuan** [mindspore-lab/mindyolo#266]
【附：单卡可以跑通，npu使用正常】
版本信息：
驱动固件：7.0.0
cann:7.0.rc1.3
mindspore:2.2.1

**Comment by zhanghuiyao** [comment]
loss正常打印说明已经成功开始训练了 aicore的显示问题 可以在Ascend 社区提问看看哈
