### ISSUE TITLE
【yolov5】单机八卡 性能劣化

### ISSUE THREAD

**Issue by Walker-yuan** [mindspore-lab/mindyolo#267]
版本信息：
CANN 7.0.0
mindspore 2.2.10
存在overflow问题，性能存在劣化，前45步时间正常0.7s左右，后面每step时间基本在30s左右

**Comment by zhanghuiyao** [comment]
运行的时候可以检查下cpu的负载 如果负载比较重 可以尝试降低数据处理的work数
[num_parallel_workers](https://github.com/mindspore-lab/mindyolo/blob/master/configs/yolov8/hyp.scratch.high.yaml#L24)
