### ISSUE TITLE
yoloV8的八卡训练找不到RANK_ID

### ISSUE THREAD

**Issue by oxdeaMind** [mindspore-lab/mindyolo#272]
mindspore:2.2.10
cann:7.1.0.3
/device Ascend 910B
/device CPU kunpeng920
执行步骤：
![image](https://github.com/mindspore-lab/mindyolo/assets/162659272/c7f292a2-cfbb-4f38-a90f-0f65399762c9)

关联用例
代码链接：https://github.com/mindspore-lab/mindyolo/tree/master/configs/yolov8
![image](https://github.com/mindspore-lab/mindyolo/assets/162659272/3bbd5255-d133-463b-a3fc-979e221e5736)
![image](https://github.com/mindspore-lab/mindyolo/assets/162659272/7f10e69d-138b-408b-a23b-60b1db4e7039)

**Comment by zhanghuiyao** [comment]
第一张截图来看起来是OOM的报错，第二个应该是torch.distributed内部的报错
<img width="900" alt="image" src="https://github.com/mindspore-lab/mindyolo/assets/20476835/4254aa31-5d29-4fcb-bfb9-1332d38d80ad">
<img width="965" alt="image" src="https://github.com/mindspore-lab/mindyolo/assets/20476835/7279d23a-51ae-43d5-821b-20fa6da797a2">

**Comment by oxdeaMind** [comment]
已经解决了
