### ISSUE TITLE
RuntimeError: Unsupported device target Ascend.

### ISSUE THREAD

**Issue by lonngxiang** [mindspore-lab/mindyolo#273]
运行demo/predict.py 报错

    self._context_handle.set_param(param, value)
RuntimeError: Unsupported device target Ascend. This process only supports one of the ['CPU']. Please check whether the Ascend environment is installed and configured correctly, and check whether current mindspore wheel package was built with "-e Ascend". For details, please refer to "Device load error message".

----------------------------------------------------
- Device load error message:
----------------------------------------------------
Load dynamic library: libmindspore_ascend.so.2 failed. libge_runner.so: cannot open shared object file: No such file or directory
Load dynamic library: libmindspore_ascend.so.1 failed. libge_runner.so: cannot open shared object file: No such file or directory

----------------------------------------------------
- C++ Call Stack: (For framework developers)
----------------------------------------------------
mindspore/core/utils/ms_context.cc:327 SetDeviceTargetFromInner

**Comment by zhanghuiyao** [comment]
看起来是mindspore和cann安装的问题，可以尝试运行以下代码check mindspore是否能正常调用ascend

>>> import mindspore as ms;ms.run_check()

**Comment by lonngxiang** [comment]
> ```python
> ms.run_check()
> ```

![image](https://github.com/mindspore-lab/mindyolo/assets/40717349/3ed0c9b7-ec48-4caa-9753-4551512bd0fb)

**Comment by lonngxiang** [comment]
这是算有问题吗

**Comment by zhanghuiyao** [comment]
是的 看起来mindspore无法检测到ascend，只能调用到cpu
<img width="881" alt="image" src="https://github.com/mindspore-lab/mindyolo/assets/20476835/32fa6fcc-e0f6-4dac-a987-ba95f25f6b1c">

**Comment by zhanghuiyao** [comment]
可以尝试按照 [官网](https://www.mindspore.cn/) 的流程进行MindSpore和CANN的安装，如果仍然有问题可以到Ascend官网和 [MindSpore开源仓](https://gitee.com/mindspore/mindspore) 上提交issue

**Comment by fookhsu** [comment]
请问下后续有解决吗，我也遇到类似的问题

**Comment by nap41h** [comment]
我也遇到了同样的问题，想问下楼主最后解决了吗
