### ISSUE TITLE
-bash: mpirun: command not found

### ISSUE THREAD

**Issue by zyfengaa** [mindspore-lab/mindyolo#274]
mpirun --allow-run-as-root  -n 8 python train.py --config ./configs/yolov7/yolov7.yaml --device_target Ascend --is_parallel True
分布式训练没有mpirun 指令，单卡可以跑通yolov7

**Comment by zhanghuiyao** [comment]
`mpirun`是一个第三方包 可以尝试按照官网文档进行安装
https://github.com/mindspore-lab/mindyolo/blob/master/docs/en/installation.md
https://www.open-mpi.org/software/ompi/v4.0/

**Comment by CarlCypress** [comment]
> `mpirun`是一个第三方包 可以尝试按照官网文档进行安装 https://github.com/mindspore-lab/mindyolo/blob/master/docs/en/installation.md https://www.open-mpi.org/software/ompi/v4.0/

我参考了以上文章，在启智平台上无法安装这个openmpi-4.0.3。主要问题是相关依赖的包无法安装，例如：gcc、mpi4py等。
此外，使用sudo执行配置时，也无法进行。。
