### ISSUE TITLE
【成都AICC】300V Pro上跑YOLOV8推理样例报错：Get op info json suffix path failed, soc_version: Ascend310P3

### ISSUE THREAD

**Issue by Madeline99** [mindspore-lab/mindyolo#275]
一、问题现象：
在300V Pro上基于minyolo跑yolov8推理样例，报错：[ERROR] KERNEL(90948,fffdbae749f0,python):2024-03-19-17:40:09.790.450 [mindspore/ccsrc/kernel/oplib/op_info_utils.cc:172] LoadOpInfoJson] Get op info json suffix path failed, soc_version: Ascend310P3
[ERROR] KERNEL(90948,fffdbae749f0,python):2024-03-19-17:40:09.790.546 [mindspore/ccsrc/kernel/oplib/op_info_utils.cc:111] GenerateOpInfos] Load op info json failed, version: Ascend310P3

![image](https://github.com/mindspore-lab/mindyolo/assets/92360741/28664ee5-c2c3-4c18-b1f2-12b0d30e623c)

二、软件版本:
-- CANN 版本: 7.0.0.alpha002
-- MindSpore 版本: 2.1.0
-- Python 版本 : 3.8.13
-- mindyolo版本：0.3.0
--操作系统版本 : Kylinv10

**Comment by zhanghuiyao** [comment]
mindyolo当前暂时不支持在310p上进行在线推理，可以尝试使用mslite方式运行
https://github.com/mindspore-lab/mindyolo/blob/master/deploy/README.md
