### ISSUE TITLE
加载VOC数据集时找不到图片

### ISSUE THREAD

**Issue by clipperscrs** [mindspore-lab/mindyolo#276]
将VOC标签转换为YOLO标签格式，文件夹转换为COCO格式后报错：Traceback (most recent call last):
  File "/home/jiasj/chenruoshui/mindyolo-master/mindyolo-master/train.py", line 321, in <module>
    train(args)
  File "/home/jiasj/chenruoshui/mindyolo-master/mindyolo-master/train.py", line 132, in train
    _dataset = COCODataset(
  File "/home/jiasj/chenruoshui/mindyolo-master/mindyolo-master/mindyolo/data/dataset.py", line 115, in __init__
    raise Exception(f"Error loading data from {self.path}: {e}\n")
Exception: Error loading data from /home/jiasj/chenruoshui/mindyolo-master/mindyolo-master/mindyolo/dataset/VOC2012/train2012.txt: No images found
![image](https://github.com/mindspore-lab/mindyolo/assets/162244894/91840d86-4e72-4fd1-a440-88e75b702524)

![image1](https://github.com/mindspore-lab/mindyolo/assets/162244894/34e72276-dd87-4c9b-9852-a5bb95abe375)

**Comment by clipperscrs** [comment]
![Uploading eEDwjfSvTg.jpg…]()

**Comment by clipperscrs** [comment]
![eEDwjfSvTg](https://github.com/mindspore-lab/mindyolo/assets/162244894/ad285778-02e9-437e-9c81-ba0593da0faf)

**Comment by yuedongli1** [comment]
train2012.txt里面应该是相对当前目录的图片路径
