### ISSUE TITLE
yolov5 bug in GPU

### ISSUE THREAD

**Issue by WangFengtu1996** [mindspore-lab/mindyolo#280]
* 使用coco 2017 训练模型，出现loss -> nan 的情况，在pynative 下debug 

https://github.com/mindspore-lab/mindyolo/blob/8228636c35b52d571d63713af7f2eb199e2698c1/mindyolo/models/losses/yolov5_loss.py#L105C1-L106C1

其中tmask 出现了全零的情况。
![image](https://github.com/mindspore-lab/mindyolo/assets/21277368/f8ea2ae8-1616-4f1b-a42f-3f0eb6ee4b29)

**Comment by WangFengtu1996** [comment]
关闭 amp。

**Comment by zhanghuiyao** [comment]
1、`tmask` 是在 `def build_targets` 函数中进行bbox matching的，是否可能是这个样本本身没存在相应的target
2、pynative模式进行调试的时候可以把同步执行打开以排除异步执行带来的问题，pynative_synchronize=True
https://www.mindspore.cn/docs/zh-CN/r2.2/api_python/mindspore/mindspore.set_context.html?highlight=pynative_synchronize

**Comment by WangFengtu1996** [comment]
@zhanghuiyao  
我这边使用的是visdrone 公开的数据集，不太可能是数据的问题，我这关闭混合精度训练  
```
# configs/yolov5/yolov5s.yaml
ms_amp_level: O0
```

**Comment by zhanghuiyao** [comment]
可以尝试在[def build_targets](https://github.com/mindspore-lab/mindyolo/blob/master/mindyolo/models/losses/yolov5_loss.py#L136) 函数中debug看下是哪一步导致的 `tmasks` 出现全0

**Comment by WangFengtu1996** [comment]
关于这部分代码，我理解只会影响到这个训练速度对吧？ 对功能是否正确并不影响？

**Comment by zhanghuiyao** [comment]
我理解这个地方主要看的是正确性的问题，`tmask`为全0会导致loss里面除 `0` `tmask.sum()`

**Comment by WangFengtu1996** [comment]
除零会导致溢出，我理解应该是使用半精度，存在的问题，关闭了amp  `ms_amp_level: O0`后，不再出现loss 为nan的问题。可能其他的 amp 等级也能解决这个问题，我比较极端的设置为0， 使用全fp32 去训练这个模型。这样子，我理解只会训练的慢一点。

我现在的问题是出现这个loss 不减小，收敛不了的问题。

我要不把这个issue 关闭，然后 在 https://github.com/mindspore-lab/mindyolo/issues/279?notification_referrer_id=NT_kwDOAUSquLQxMDA3NDE2MzQzOToyMTI3NzM2OA#issue-2217373679 这个issue 中跟踪。

**Comment by zhanghuiyao** [comment]
> 除零会导致溢出，我理解应该是使用半精度，存在的问题，关闭了amp `ms_amp_level: O0`后，不再出现loss 为nan的问题。可能其他的 amp 等级也能解决这个问题，我比较极端的设置为0， 使用全fp32 去训练这个模型。这样子，我理解只会训练的慢一点。
> 
> 我现在的问题是出现这个loss 不减小，收敛不了的问题。
> 
> 我要不把这个issue 关闭，然后 在 #279 这个issue 中跟踪。

如果是mix-precision导致的问题 可以尝试将loss部分用fp32运算，其他的保持不变，另外mindyolo中的amp默认用的应该就是O0
https://github.com/mindspore-lab/mindyolo/blob/master/train.py#L31C60-L31C61

**Comment by WangFengtu1996** [comment]
* yaml 这个优先级是比较高，我更改的这个地方
https://github.com/mindspore-lab/mindyolo/blob/8228636c35b52d571d63713af7f2eb199e2698c1/configs/yolov5/yolov5s.yaml#L11

**Comment by WangFengtu1996** [comment]
loss默认是fp32

https://github.com/mindspore-lab/mindyolo/blob/8228636c35b52d571d63713af7f2eb199e2698c1/train.py#L196

**Comment by zhanghuiyao** [comment]
> * yaml 这个优先级是比较高，我更改的这个地方
>   https://github.com/mindspore-lab/mindyolo/blob/8228636c35b52d571d63713af7f2eb199e2698c1/configs/yolov5/yolov5s.yaml#L11

可以的
