### ISSUE TITLE
关于默认使用学习率，使用的是一个固定学习率？

### ISSUE THREAD

**Issue by WangFengtu1996** [mindspore-lab/mindyolo#281]
* 从下面这个函数来看, 这个学习率使用的是固定学习率？
https://github.com/mindspore-lab/mindyolo/blob/8228636c35b52d571d63713af7f2eb199e2698c1/mindyolo/optim/scheduler.py#L7
* 在log 中的学习率，是一个动态变化的学习率
![image](https://github.com/mindspore-lab/mindyolo/assets/21277368/d8e9cef6-932e-40f7-988e-46c4e774c4b8)

* 在gpu上 visdrone  yolov5 loss 一直不下降
![image](https://github.com/mindspore-lab/mindyolo/assets/21277368/da97acc9-09cb-46ec-9b93-a5ab263ac4ee)

**Comment by yuedongli1** [comment]
每个模型都有自己的学习率衰减策略，GPU上的性能没有全量验证过
