### ISSUE TITLE
某些特殊数据集训练无效的问题

### ISSUE THREAD

**Issue by zhouyifeng888** [mindspore-lab/mindyolo#295]
这是目前碰到问题的数据集：https://robotics.pkusz.edu.cn/resources/dataset/
![image](https://github.com/mindspore-lab/mindyolo/assets/55791015/7a235043-7f70-4631-9da8-7b44acd5cdcb)

尝试了yolov5（5s）和yolov8（8s、8l）模型，发现训练这个数据集都没有效果，不论怎么训练，map都是0，在训练集上的map都是0，训练过程中，要么loss出现nan，要么loss收敛效果很不明显，要么loss收敛看上去是比较明显的，但是map也都是为0，或者就是直接提示检测出0个bbox，而同样这个数据集，我测试了pytorch的yolov5s的代码，训练效果非常好，也试了下其它框架实现的一些yolo模型，效果也很好，所以我猜测mindyolo这边的模型实现是不是对于某些特殊数据集没有适配好？

当然我也去测试了下models仓库里的那个yolov5s模型，那个代码loss没有nan，收敛也比较明显的（从一开始的好几千收敛到20多），但map依旧是0，所以我还有另一个猜测，是不是这数据集的数值比较特殊或者极端，触发了mindspore框架的什么bug?

目前调试mindyolo里的yolov5s代码，定位到了loss出现nan的其中一个原因：
<img width="761" alt="140c5d99c238edf42d8c585aec918df" src="https://github.com/mindspore-lab/mindyolo/assets/55791015/25ba59cf-10ee-4d4a-9d68-06610add9c1c">
截图中的tmask在某些极端一点的数据集上确实会有问题，如果全都只有小目标，大目标一个也没有，这里的这个tmask就会出现全为0的情况，然后就出现除0操作，loss就成nan了；当然我这次训练map一直为0的原因，应该不止这一个，yolov8的loss实现不一样的，但也是训练不起来，其它具体原因目前我还没什么思路。

**Comment by yuedongli1** [comment]
可否提供下代码仓，或者发下数据集相关配置

**Comment by zhouyifeng888** [comment]
> 可否提供下代码仓，或者发下数据集相关配置

我没单独开代码仓，代码就是mindyolo直接拉下来的，没改啥配置，直接就是加了个数据集的配置文件，这行命令启动训练，python train.py --device_target GPU --weight ./yolov5s_300e_mAP376-860bcf3b.ckpt --epochs 100 --config ./configs/yolov5/yolov5s.yaml --ms_amp_level O0 --run_eval True --per_batch_size 64 --img_size 640

![image](https://github.com/mindspore-lab/mindyolo/assets/55791015/716a9e8d-3f9f-4834-8755-a3c7fa798597)
![image](https://github.com/mindspore-lab/mindyolo/assets/55791015/3e62ef37-0860-4ffb-afa8-7e90658a0a91)

数据集格式我自己转换成了yolo的格式，和pytorch yolov5的那个代码用的数据格式一致

**Comment by yuedongli1** [comment]
可以关注一下计算map时，是否有权重未导入，或者用demo/predict.py做下可视化推理看看

**Comment by zhouyifeng888** [comment]
> 可以关注一下计算map时，是否有权重未导入，或者用demo/predict.py做下可视化推理看看

应该不是这个问题，去年我做其它任务也跑过别的数据集，有的数据集就是正常的，没改过代码，都是一样使用的

**Comment by zhouyifeng888** [comment]
> 可以关注一下计算map时，是否有权重未导入，或者用demo/predict.py做下可视化推理看看
并且应该也不存在权重未导入的情况，训练出来的模型本身内存里就带着权重去eval的，而且有时候map为0，有时候bbox的数量直接为0，就不计算权重了，说明权重就在训练过程中变化了，但就是有问题

**Comment by zhouyifeng888** [comment]
> 可以关注一下计算map时，是否有权重未导入，或者用demo/predict.py做下可视化推理看看

并且应该也不存在权重未导入的情况，训练出来的模型本身内存里就带着权重去eval的，而且有时候map为0，有时候bbox的数量直接为0，就不计算权重了，说明权重就在训练过程中变化了，但就是有问题

**Comment by zhouyifeng888** [comment]
通过直接predict.py打印框框看了下，这里用的是训练了20个epoch权重文件，torch的yolov5s是训练到第2个epoch时map就大于0了，python predict.py --config ./configs/yolov5/yolov5s.yaml --weight=runs/2024.05.26-16.10.23/weights/yolov5s-22_57.ckpt --image_path ../PCB_DATASET_YOLO/train/images/0.jpg --device_target=GPU --ms_amp_level O0 --conf_thres 0.01  必须把置信度设置到0.01才能出框，并且预测的全是错的，类别全错，一共5个类别，预测值都是最后一个类别（实际我测的都是类别ID为0到3的图片），测试了多张图片，预测值都是最后一个类别（最后一个类别ID为4）
<img width="742" alt="a8b5a59d81d3787689127e108f5bf28" src="https://github.com/mindspore-lab/mindyolo/assets/55791015/29885b90-70c2-47c8-9e00-1ca7278466ef">

我通过打印日志和torch的yolov5s对比了下，发现数据集的处理方式不一样，传入loss的targets是不一样的，然后loss的计算上和torch版有差异，感觉主要就是这个targets的处理的差异
![image](https://github.com/mindspore-lab/mindyolo/assets/55791015/30ccf0be-a4d8-43fc-a8b1-c20a8a08b742)
![image](https://github.com/mindspore-lab/mindyolo/assets/55791015/8cfc3c69-2cad-4dcc-a3fd-354d2ceac874)

**Comment by tomzw11** [comment]
> 我通过打印日志和torch的yolov5s对比了下，发现数据集的处理方式不一样，传入loss的targets是不一样的，然后loss的计算上和torch版有差异，感觉主要就是这个targets的处理的差异
具体是什么差异呢

**Comment by zhouyifeng888** [comment]
> > 我通过打印日志和torch的yolov5s对比了下，发现数据集的处理方式不一样，传入loss的targets是不一样的，然后loss的计算上和torch版有差异，感觉主要就是这个targets的处理的差异
> 
> 具体是什么差异呢

处理方式不同呀，shape都不一样

**Comment by zhouyifeng888** [comment]
> > > 我通过打印日志和torch的yolov5s对比了下，发现数据集的处理方式不一样，传入loss的targets是不一样的，然后loss的计算上和torch版有差异，感觉主要就是这个targets的处理的差异
> > 
> > 
> > 具体是什么差异呢
> 
> 处理方式不同呀，shape都不一样

里面具体的逻辑含义，我 不清楚
