### ISSUE TITLE
非命令行方法进行推理

### ISSUE THREAD

**Issue by asdfo123** [mindspore-lab/mindyolo#321]
如题，请问有无非命令行方法，直接在Python中类似调用API的形式直接进行推理，获得预测值的predict_list这样的使用方法呢？

**Comment by Ash-Lee233** [comment]
https://github.com/mindspore-lab/mindyolo/blob/master/demo/predict.py

可以参考该脚本，在mindyolo.utils中提供了多种评估所需函数可以调用
