### ISSUE TITLE
打扰下作者 我是新手python demo/predict.py --config ./configs/yolov5/yolov5n.ya ml --weight=/tmp/insect_detect_mindyolo/weight/yolov5m_300e_mAP449-e7bbf695.ckpt --image_path ./image/2.jp g --device_target=CPU 不管使用哪个权重文件均会报错For 'load_param_into_net', model.model.24.m.0.weight in the argument 'net' should have the same shape as model.model.24.m.0.weight in the argument 'parameter_dict'. But got its shape (42, 192, 1, 1) in the argument 'net' and shape (255, 192, 1, 1) in the argument 'parameter_dict'.May you need to check whether the checkpoint you loaded is correct or the batch size and so on in the 'net' and 'parameter_dict' are same.

### ISSUE THREAD

**Issue by YYCYcc** [mindspore-lab/mindyolo#394]
能不能麻烦以下作者，非常非常感谢

**Comment by zhanghuiyao** [comment]
报错的意思应该是实际权重和加载权重的shape不匹配，看运行命令应该是规格没对上导致的
<img width="1165" alt="image" src="https://github.com/user-attachments/assets/ca168ba9-009f-453a-899e-e4509f0b1f1d">

⚠️ 另外mindyolo当前仅支持在 Ascend 硬件上运行，其他平台 (e.g. CPU/GPU) 均未验证，有可能出现一些不可预期的问题。

**Comment by YYCYcc** [comment]
抱歉作者我截错内容了 但是权重的确存在问题 python demo/predict.py --config ./configs/yolov5/yolov5s.yaml --weight=/tmp/insect_detect_mindyolo/weight/yolov5s_300e_mAP376-df4a45b6-910v2.ckpt --image_path ./image/2.jpg --device_target=CPU
2024-12-02 08:41:57,677 [WARNING] Parse Model, args: nearest, keep str type
2024-12-02 08:41:57,734 [WARNING] Parse Model, args: nearest, keep str type
2024-12-02 08:41:57,923 [INFO] number of network params, total: 7.062949M, trainable: 7.043902M
[WARNING] ME(116565:139638527563392,MainProcess):2024-12-02-08:41:58.198.532 [mindspore/train/serialization.py:928] For 'load_param_into_net', remove parameter prefix name: ema., continue to load.
[CRITICAL] ME(116565:139638527563392,MainProcess):2024-12-02-08:41:58.207.702 [mindspore/train/serialization.py:115] Failed to combine the net and the parameters for param model.model.24.m.0.weight.
Traceback (most recent call last):
  File "demo/predict.py", line 333, in <module>
    infer(args)
  File "demo/predict.py", line 280, in infer
    checkpoint_path=args.weight,
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindyolo/models/model_factory.py", line 38, in create_model
    load_param_into_net(model, checkpoint_param)
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindspore/train/serialization.py", line 895, in load_param_into_net
    _load_dismatch_prefix_params(net, parameter_dict, param_not_load, strict_load)
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindspore/train/serialization.py", line 934, in _load_dismatch_prefix_params
    _update_param(param, new_param, strict_load)
  File "/usr/local/python-3.7.5/lib/python3.7/site-packages/mindspore/train/serialization.py", line 121, in _update_param
    raise RuntimeError(msg)
RuntimeError: For 'load_param_into_net', model.model.24.m.0.weight in the argument 'net' should have the same shape as model.model.24.m.0.weight in the argument 'parameter_dict'. But got its shape (42, 128, 1, 1) in the argument 'net' and shape (255, 128, 1, 1) in the argument 'parameter_dict'.May you need to check whether the checkpoint you loaded is correct or the batch size and so on in the 'net' and 'parameter_dict' are same.
可能是因为我用cpu跑代码的原因马

**Comment by yuedongli1** [comment]
这个是由于数据集类别数和coco数据集不一致导致的，coco数据集类别数为80，从报错信息推测你在数据集的yaml中设置的类别数为9

**Comment by YYCYcc** [comment]
我是下载的[https://tools.obs.cn-south-292.ca-aicc.com:443/samples/insect_detect/insect_coco.tar](https://gitee.com/link?target=https%3A%2F%2Ftools.obs.cn-south-292.ca-aicc.com%3A443%2Fsamples%2Finsect_detect%2Finsect_coco.tar)这个数据ji,他的coco_class.txt文件中的数据集种类为9，能请教一下您，我应该怎么去修改吗 ？万分感谢！！

**Comment by WongGawa** [comment]
可以参考examples文件夹下的用例，编写yaml配置文件的内容进行修改。

**Comment by YYCYcc** [comment]
好的谢谢作者！！！万分感谢 科研路上有你真美丽😍
